version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: tajbiul_rawol
      POSTGRES_PASSWORD: BlogApp123
      POSTGRES_DB: BlogDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      DB_USER: tajbiul_rawol
      DB_HOST: db
      DB_NAME: BlogDB
      DB_PASSWORD: BlogApp123
      DB_PORT: 5432
      PORT: 3000
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    depends_on:
      - api

volumes:
  db_data:
